name: Generate Snake

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ajudantejose

          outputs: |
            dist/github-snake.svg?color_snake=#000000&color_dots=#ebedf0,#9e9e9e,#707070,#404040,#000000
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#ffffff&color_dots=#161b22,#30363d,#6e7681,#b1bac4,#f0f6fc

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
